package ejercicio91;

public class PersonalNumberException extends Exception {
	
	private String mensaje;
	
	public PersonalNumberException (){
		this.mensaje= "Se ha producido una PersonalNumberException";
	}

	public String getMensaje() {
		return "Se ha producido una PersonalNumberException";
	}
}